site_name: pit-blog
site_description: все самое лучшее
copyright: Made with ❤️ by Karan +++.
site_url: https://sepia123.netlify.app/
repo_name: peter-hanzo/sepia/
repo_url: https://github.com/peter-hanzo/sepia/
edit_uri: edit/main/docs/
docs_dir: ./docs
site_dir: ./site
# P
theme:
    # https://squidfunk.github.io/mkdocs-material/creating-your-site/#configuration
    name: material
    logo: assets/ava-40.svg
    favicon: assets/ava-gol-favicon.png
    # https://squidfunk.github.io/mkdocs-material/customization/#extending-the-theme
    custom_dir: overrides
    # https://squidfunk.github.io/mkdocs-material/setup/changing-the-fonts/
    font:
      text: Inter
      code: Roboto Mono
      # Noto Sans, Spectral, -apple-system, Inter,Helvetica Neue,Helvetica, Roboto
      # IMB Plex Mono, Cascadia, Roboto Mono
    language: en
    shortcuts:
      next: 78 # n
      previous: 80 # p
      search: 83 # s
    # https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/
    palette:
      # P
      # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
      # P       
      # Dark mode    
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue grey
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to light mode
# P
      features:
        - navigation.indexes
        - navigation.tabs.sticky
        - navigation.top      
        - navigation.instant
        - navigation.tracking
        - toc.follow
        - content.action.edit
        - content.action.view
        - search.share
        - search.highlight
        - search.suggest


# P
      include_search_page: true
      search_index_only: true
# P
# Extensions
markdown_extensions:
  - admonition
  - md_in_html
  - codehilite
  - meta
  - attr_list
  - footnotes

# P
  - nl2br
  - sane_lists
  - smarty
  - tables
  - mdx_breakless_lists
  - def_list
  - toc:
      title: On This Page
      toc_depth: '3'
      separator: '-'
      permalink: true
      slugify: !!python/name:pymdownx.slugs.uslugify # convert title to html-compatible text
  
  
  
# P
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.details
  - pymdownx.magiclink
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.tabbed
  - pymdownx.highlight:
      use_pygments: true
      anchor_linenums: true
  - pymdownx.tasklist:
       custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons
# P
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:mermaid2.fence_mermaid
# P

# P
# Pl
plugins:
  - search
  
  - tags:
      tags_file: Notes/tags.md

  - literate-nav:
      nav_file: SUMMARY.md

  - social:
      cards_font: Noto Sans SC
      cards_color:
        fill: "#59eb9b" 
        text: "#FFFFFF"
  
  

  
  - minify:
      minify_html: true
      htmlmin_opts:
        remove_comments: true             
# P
  - ezlinks
  - mermaid2
  - awesome-pages
  - embed_file:
      callouts: true
      custom-attributes: 'assets/css/custom_attributes.css'
  - callouts
  - git-revision-date-localized:
        type: custom
        custom_format: "%d. %B %Y"
        timezone: Europe/Amsterdam
        locale: en
        fallback_to_build_date: true
        enable_creation_date: false
        exclude:
            - index.md
            - tags.md
        
        
        
        
  - encryptcontent:
      title_prefix: '🔐'
      password_button: True
      password_button_text: '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512" height="1em" width="1em"><!--! Font Awesome Pro 6.1.1 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license (Commercial License) Copyright 2022 Fonticons, Inc. --><path d="M416 32h-64c-17.67 0-32 14.33-32 32s14.33 32 32 32h64c17.67 0 32 14.33 32 32v256c0 17.67-14.33 32-32 32h-64c-17.67 0-32 14.33-32 32s14.33 32 32 32h64c53.02 0 96-42.98 96-96V128C512 74.98 469 32 416 32zM342.6 233.4l-128-128c-12.51-12.51-32.76-12.49-45.25 0c-12.5 12.5-12.5 32.75 0 45.25L242.8 224H32C14.31 224 0 238.3 0 256s14.31 32 32 32h210.8l-73.38 73.38c-12.5 12.5-12.5 32.75 0 45.25s32.75 12.5 45.25 0l128-128C355.1 266.1 355.1 245.9 342.6 233.4z"/></svg>'
  - custom-attributes:
      file: 'assets/css/custom_attributes.css'
  - meta-descriptions
hooks:
  - overrides/hooks/on_page_markdown.py
  
extra_javascript:
  - assets/js/mathjax.js
  - assets/js/utils.js
  - assets/js/wiki_hover.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra_css:
    - assets/css/template/blog.css
    - assets/css/template/grid.css
    - assets/css/template/img-grids-float.css
    - assets/css/template/tooltipster.bundle.min.css
    - assets/css/template/utils.css
    - assets/css/admonition.css
    - assets/css/custom_attributes.css
    - assets/css/customization.css
    - stylesheets/extra.css

# P

# P
extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/mr-karan
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/mrkaran_
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/dirigible.io
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/groups/8413366
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/c/dirigibleio
      
    - icon: fontawesome/brands/github-alt
      link: https://github.com/mr-karan
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/mrkaran_
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/dirigible.io
    - icon: fontawesome/brands/linkedin
      link: https://www.youtube.com/c/dirigibleio
    - icon: fontawesome/brands/instagram
      link: https://www.youtube.com/c/dirigibleio
    - icon: fontawesome/brands/product-hunt
      link: https://www.youtube.com/c/dirigibleio
    - icon: fontawesome/solid/paper-plane
      link: mailto:<rur@tut.by>
      
      
      
# P
  generator: false
